### ISSUE TITLE
Broken after WP 4.5.3  and/or WC 2.6.3 update

### ISSUE THREAD

**Issue by yeldarb420** [deadlyhifi/woocomm-nested-layered-nav#1]
I am using this plugin in a site I was working on months ago. Just started working on it again after awhile , After updating wordpress & woocommerce to the latest & this has stopped working. I have played it with for about 1.5 days & can't figure out what has it failing with the recent updates. Any help to solve this issue would be greatly appreciated, worked GREAT before. Will report back if I figure out anything myself. -Brad

**Comment by deadlyhifi** [comment]
Hi Brad, I'm away from my computer for the next week so won't be able to look into it.

I just took the existing plugin included in woocom and found the points to insert a `<ul>` after an opening `<li>` if there were children. I don't really use this anymore but will have a look when I can, but like I say, won't be for at least a week.
